version: '3'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./containerdata/postgresql_data:/var/lib/postgresql/data
    logging:
        driver: none
  app:
    build: .
    depends_on:
      - db

