"""first migration

Revision ID: 58187538593d
Revises: 
Create Date: 2024-06-13 13:58:58.911067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58187538593d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
